"""
app.py — Provenance Guard Flask application

Routes:
  POST /api/analyze  — run both signals, aggregate, persist, return scored response
  POST /api/appeal   — (stub placeholder, implemented in M5)
  GET  /api/log      — (stub placeholder, implemented in M5)

M4: Signal 2 (stylometrics) and full aggregation are live.
"""

import logging
import os
import uuid
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from database import init_db, insert_submission, insert_audit_event, get_recent_submissions
from pipeline import run_llm_signal, run_stylo_signal, aggregate_signals

load_dotenv()
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate limiter
# ---------------------------------------------------------------------------
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

# ---------------------------------------------------------------------------
# DB init on startup
# ---------------------------------------------------------------------------
with app.app_context():
    init_db()


# ---------------------------------------------------------------------------
# Helpers — transparency label (verbatim strings from planning.md §3)
# ---------------------------------------------------------------------------
_LABEL_AI_HIGH = (
    "Our analysis indicates this content was likely generated by an AI writing tool. "
    "Two independent signals (a language model assessment and a structural text "
    "analysis) both point toward AI authorship with high agreement. If you are the "
    "author and believe this is incorrect, you can submit an appeal."
)

_LABEL_HUMAN_HIGH = (
    "Our analysis indicates this content was likely written by a human. Two "
    "independent signals (a language model assessment and a structural text "
    "analysis) both point toward human authorship with high agreement."
)

_LABEL_UNCERTAIN = (
    "Our analysis could not confidently determine whether this content was written "
    "by a human or generated by an AI tool. The signals we use gave conflicting or "
    "inconclusive results. This label is not an accusation; it reflects the limits "
    "of automated detection. If you are the author, you can submit an appeal with "
    "context about how you created this work."
)


def _build_label(classification: str, confidence_level: str, stylo_reliable: bool) -> str:
    """
    Return the exact label string from planning.md §3.

    Variant A: classification=ai_generated  AND confidence_level=high
    Variant B: classification=human_written AND confidence_level=high
    Variant C: everything else (uncertain)

    When stylo_reliable=False we only have one signal, so we can never
    claim Variant A/B even if the score is extreme — that would be
    misleading.  We use _LABEL_UNCERTAIN with a note instead.
    """
    if not stylo_reliable:
        # Single-signal result: cap at Uncertain wording but note the score
        return (
            "Our analysis could not confidently determine whether this content was "
            "written by a human or generated by an AI tool. The text was too short "
            "to run a full structural analysis — only the language model signal was "
            "used. If you are the author, you can submit an appeal."
        )
    if classification == "ai_generated" and confidence_level == "high":
        return _LABEL_AI_HIGH
    if classification == "human_written" and confidence_level == "high":
        return _LABEL_HUMAN_HIGH
    return _LABEL_UNCERTAIN


# ---------------------------------------------------------------------------
# POST /api/analyze
# ---------------------------------------------------------------------------
@app.route("/api/analyze", methods=["POST"])
@limiter.limit("10 per minute")
def analyze():
    """
    Required JSON fields:
      content   (str) — text to analyze
    Optional:
      title     (str) — stored, not analyzed
      author_id (str) — stored for audit trail
    """
    data = request.get_json(silent=True)

    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    content = data.get("content", "").strip()
    if not content:
        return jsonify({"error": "Missing required field: content"}), 400

    title     = data.get("title",     "")
    author_id = data.get("author_id", "")

    # ── Signal 1: Groq LLM ──────────────────────────────────────────────────
    signal1   = run_llm_signal(content)
    llm_score = signal1["llm_score"]

    # ── Signal 2: Stylometric heuristics (pure Python, no network) ───────────
    signal2    = run_stylo_signal(content)
    stylo_score = signal2["stylo_score"]

    # ── Aggregation: weighted combination + signal-gap check (spec §1 + §2) ──
    agg = aggregate_signals(content, llm_score, stylo_score)
    composite_score  = agg["composite_score"]
    confidence_level = agg["confidence_level"]
    classification   = agg["classification"]
    signal_gap       = agg["signal_gap"]
    stylo_reliable   = agg["stylo_reliable"]

    # ── Transparency label (verbatim strings from spec §3) ───────────────────
    transparency_label = _build_label(classification, confidence_level, stylo_reliable)

    # ── Identifiers + timestamp ──────────────────────────────────────────────
    content_id = str(uuid.uuid4())
    now_iso    = datetime.now(timezone.utc).isoformat()
    word_count = len(content.split())

    # ── Persist to submissions table ─────────────────────────────────────────
    insert_submission({
        "content_id":         content_id,
        "author_id":          author_id,
        "title":              title,
        "content_snippet":    content[:500],
        "classification":     classification,
        "confidence_score":   composite_score,
        "confidence_level":   confidence_level,
        "llm_score":          llm_score,
        "stylo_score":        stylo_score,
        "signal_gap":         signal_gap,
        "stylo_reliable":     1 if stylo_reliable else 0,
        "transparency_label": transparency_label,
        "status":             "active",
        "created_at":         now_iso,
    })

    # ── Persist to audit_log ─────────────────────────────────────────────────
    insert_audit_event({
        "content_id":              content_id,
        "event_type":              "analysis",
        "appeal_id":               None,
        "reason":                  None,
        "previous_classification": None,
        "previous_confidence":     None,
        "status":                  "active",
        "timestamp":               now_iso,
    })

    logger.info(
        "Analyzed content_id=%s  llm=%.4f  stylo=%.4f  composite=%.4f  "
        "gap=%s  classification=%s  confidence=%s",
        content_id, llm_score, stylo_score, composite_score,
        f"{signal_gap:.4f}" if signal_gap is not None else "N/A",
        classification, confidence_level,
    )

    # ── API response (spec §6) ───────────────────────────────────────────────
    return jsonify({
        "content_id":         content_id,
        "classification":     classification,
        "confidence_score":   composite_score,
        "confidence_level":   confidence_level,
        "transparency_label": transparency_label,
        "signals": {
            "llm_score":         llm_score,
            "llm_reasoning":     signal1["reasoning"],
            "llm_fallback":      signal1["fallback"],
            "stylo_score":       stylo_score,
            "stylo_slv":         signal2["slv_score"],
            "stylo_ttr":         signal2["ttr_score"],
            "signal_gap":        signal_gap,
            "text_length_words": word_count,
            "stylo_reliable":    stylo_reliable,
        },
        "status":    "active",
        "timestamp": now_iso,
    }), 200


# ---------------------------------------------------------------------------
# POST /api/appeal  — placeholder
# ---------------------------------------------------------------------------
@app.route("/api/appeal", methods=["POST"])
@limiter.limit("5 per minute")
def appeal():
    """Placeholder — implemented in M5."""
    return jsonify({"error": "Not implemented yet"}), 501


# ---------------------------------------------------------------------------
# GET /api/log  (also aliased as GET /log for checkpoint curl convenience)
# ---------------------------------------------------------------------------
@app.route("/api/log", methods=["GET"])
@app.route("/log", methods=["GET"])
@limiter.limit("30 per minute")
def log():
    """
    Return the most recent audit log entries as JSON.
    Query params:
      limit (int, default 50) — max entries to return
    """
    limit = min(int(request.args.get("limit", 50)), 200)
    rows  = get_recent_submissions(limit)

    entries = [
        {
            "content_id":  r["content_id"],
            "creator_id":  r["author_id"],
            "timestamp":   r["created_at"],
            "attribution": r["classification"],
            "confidence":  r["confidence_score"],
            "llm_score":   r["llm_score"],
            "status":      r["status"],
        }
        for r in rows
    ]

    return jsonify({"entries": entries, "total": len(entries)}), 200


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    app.run(debug=True, port=5000)

