"""
app.py — Provenance Guard Flask application

Routes defined here:
  POST /api/analyze  — accept text, validate fields, return stub response (Signal logic added in next step)
  POST /api/appeal   — (stub placeholder, not implemented yet)
  GET  /api/log      — (stub placeholder, not implemented yet)
"""

import os
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# ---------------------------------------------------------------------------
# Rate limiter
# ---------------------------------------------------------------------------
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],          # no global default; limits set per route
    storage_uri="memory://",    # in-process storage for MVP
)

# ---------------------------------------------------------------------------
# POST /api/analyze
# ---------------------------------------------------------------------------
@app.route("/api/analyze", methods=["POST"])
@limiter.limit("10 per minute")
def analyze():
    """
    Accept a JSON body, validate required fields, and return a hardcoded stub
    response so the route wiring can be verified before any signal logic is added.

    Required fields:
      - content   (str) : the text to analyze
    Optional fields:
      - title     (str) : stored but not analyzed
      - author_id (str) : stored for audit trail
    """
    data = request.get_json(silent=True)

    # --- input validation ---------------------------------------------------
    if not data:
        return jsonify({"error": "Request body must be JSON"}), 400

    content = data.get("content", "").strip()
    if not content:
        return jsonify({"error": "Missing required field: content"}), 400

    title     = data.get("title", "")
    author_id = data.get("author_id", "")

    # --- stub response (hardcoded) ------------------------------------------
    # Replace this block in the next step when signal logic is wired in.
    stub_response = {
        "content_id":         "stub-uuid-placeholder",
        "classification":     "uncertain",
        "confidence_score":   0.5,
        "confidence_level":   "medium",
        "transparency_label": (
            "Our analysis could not confidently determine whether this content "
            "was written by a human or generated by an AI tool. "
            "(STUB — no signals run yet)"
        ),
        "signals": {
            "llm_score":          None,
            "stylo_score":        None,
            "signal_gap":         None,
            "text_length_words":  len(content.split()),
            "stylo_reliable":     None,
        },
        "status":    "active",
        "timestamp": None,
        # echo back received fields for easy inspection during testing
        "_debug": {
            "received_content_chars": len(content),
            "received_title":         title,
            "received_author_id":     author_id,
        },
    }

    return jsonify(stub_response), 200


# ---------------------------------------------------------------------------
# POST /api/appeal  — placeholder
# ---------------------------------------------------------------------------
@app.route("/api/appeal", methods=["POST"])
@limiter.limit("5 per minute")
def appeal():
    """Placeholder — implemented in M5."""
    return jsonify({"error": "Not implemented yet"}), 501


# ---------------------------------------------------------------------------
# GET /api/log  — placeholder
# ---------------------------------------------------------------------------
@app.route("/api/log", methods=["GET"])
@limiter.limit("30 per minute")
def log():
    """Placeholder — implemented in M5."""
    return jsonify({"error": "Not implemented yet"}), 501


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    app.run(debug=True, port=5000)
