"""
labels.py — Transparency label generation for Provenance Guard

Implements the three verbatim label variants from planning.md §3.
This module has no dependencies on Flask, the database, or the pipeline —
it is a pure mapping function and can be tested and imported independently.

Usage:
    from labels import generate_label
    text = generate_label(classification, confidence_level, stylo_reliable)
"""

# ---------------------------------------------------------------------------
# Verbatim label strings — planning.md §3
# Do NOT paraphrase. The exact wording was chosen deliberately.
# ---------------------------------------------------------------------------

# Variant A: High-confidence AI
LABEL_AI_HIGH: str = (
    "Our analysis indicates this content was likely generated by an AI writing tool. "
    "Two independent signals (a language model assessment and a structural text "
    "analysis) both point toward AI authorship with high agreement. If you are the "
    "author and believe this is incorrect, you can submit an appeal."
)

# Variant B: High-confidence Human
LABEL_HUMAN_HIGH: str = (
    "Our analysis indicates this content was likely written by a human. Two "
    "independent signals (a language model assessment and a structural text "
    "analysis) both point toward human authorship with high agreement."
)

# Variant C: Uncertain (also used when stylo_reliable=False)
LABEL_UNCERTAIN: str = (
    "Our analysis could not confidently determine whether this content was written "
    "by a human or generated by an AI tool. The signals we use gave conflicting or "
    "inconclusive results. This label is not an accusation; it reflects the limits "
    "of automated detection. If you are the author, you can submit an appeal with "
    "context about how you created this work."
)

# Variant D: Short-text fallback (single-signal — Uncertain family)
LABEL_SHORT_TEXT: str = (
    "Our analysis could not confidently determine whether this content was written "
    "by a human or generated by an AI tool. The text was too short to run a full "
    "structural analysis — only the language model signal was used. If you are the "
    "author, you can submit an appeal."
)


def generate_label(
    classification: str,
    confidence_level: str,
    stylo_reliable: bool = True,
) -> str:
    """
    Map a detection result to the correct transparency label string.

    Args:
        classification:   'ai_generated' | 'human_written' | 'uncertain'
        confidence_level: 'high' | 'medium' | 'low'
        stylo_reliable:   True when text was >= 50 words and both signals ran.
                          False means only the LLM signal was used.

    Returns:
        One of the four label strings defined in this module.

    Mapping (from planning.md §3 + §2 threshold table):

        classification=ai_generated  AND confidence_level=high  AND reliable
            → Variant A (LABEL_AI_HIGH)

        classification=human_written AND confidence_level=high  AND reliable
            → Variant B (LABEL_HUMAN_HIGH)

        stylo_reliable=False (text too short, one signal only)
            → Variant D (LABEL_SHORT_TEXT)  — Uncertain family

        everything else (uncertain classification, or medium/low confidence)
            → Variant C (LABEL_UNCERTAIN)
    """
    if not stylo_reliable:
        return LABEL_SHORT_TEXT

    if classification == "ai_generated" and confidence_level == "high":
        return LABEL_AI_HIGH

    if classification == "human_written" and confidence_level == "high":
        return LABEL_HUMAN_HIGH

    return LABEL_UNCERTAIN
